services:
  postgres_db:
    build:
      dockerfile: ./dockerfile
      context: .
    container_name: postgres_db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports: 
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8080:80"